services:
  cleanarchitecturetemplate.webapi:
    image: cleanarchitecturetemplate.webapi
    build:
      context: .
      dockerfile: CleanArchitectureTemplate.WebApi/Dockerfile
    ports:
        - "5000:80"
        - "5001:443"